package VIEW;
import DAO.FornecedorDAO;
import DAO.FuncionarioDAO;
import DTO.FornecedorDTO;
import DTO.FuncionarioDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class frmFornecedorView extends javax.swing.JFrame {

    /**
     * Creates new form frmFornecedorView
     */
    public frmFornecedorView() {
        initComponents();
        preenche_busca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btbCarregarCampos = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORNECEDOR");

        jLabel6.setText("Digite a Cidade:");

        jLabel9.setText("Digite o Endereço:");

        jLabel8.setText("Digite o E-mail:");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel5.setText("Digite o Telefone:");

        jLabel7.setText("Digite o Estado:");

        jLabel2.setText("Digite a Razão Social:");

        txtRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaoSocialActionPerformed(evt);
            }
        });

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Razao Social", "Telefone", "Cidade", "Estado", "Endereco", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblFornecedor);

        jLabel4.setText("ID:");

        btbCarregarCampos.setText("CARREGAR CAMPOS");
        btbCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCarregarCamposActionPerformed(evt);
            }
        });

        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndereco)
                            .addComponent(txtEstado)
                            .addComponent(txtEmail)
                            .addComponent(txtRazaoSocial)
                            .addComponent(txtTelefone)
                            .addComponent(txtCidade)
                            .addComponent(txtId)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar)
                                .addGap(148, 148, 148))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btbCarregarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOk)
                            .addComponent(btnLimpar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbCarregarCampos)
                            .addComponent(btnAlterar)
                            .addComponent(btnExcluir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        Fornecedor();
        preenche_busca();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
        preenche_busca();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaoSocialActionPerformed

    private void btbCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCarregarCamposActionPerformed
        setarCampos();
        preenche_busca();
    }//GEN-LAST:event_btbCarregarCamposActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AlterarCampos();
        preenche_busca();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ExcluirCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFornecedorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCarregarCampos;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void Fornecedor(){
        String razaosocial, endereco, cidade, estado, email, telefone;
        
        razaosocial=txtRazaoSocial.getText();
        endereco=txtEndereco.getText();
        telefone=txtTelefone.getText();
        cidade=txtCidade.getText();
        estado=txtEstado.getText();
        email=txtEmail.getText();
        
        FornecedorDTO objfornecedorDTO=new FornecedorDTO();
        objfornecedorDTO.setCidade(cidade);
        objfornecedorDTO.setEmail(email);
        objfornecedorDTO.setEndereco(endereco);
        objfornecedorDTO.setEstado(estado);
        objfornecedorDTO.setRazaosocial(razaosocial);
        objfornecedorDTO.setTelefone(telefone);
        
        FornecedorDAO objFornecedorDAO=new FornecedorDAO();
        objFornecedorDAO.cadastrarFornecedor(objfornecedorDTO);
    }
    
    private void limparCampos(){
        txtCidade.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtEstado.setText("");
        txtRazaoSocial.setText("");
        txtTelefone.setText("");
        txtId.setText("");
        
        txtRazaoSocial.requestFocus();
    }
    
    public void preenche_busca(){
        try{
            FornecedorDAO objFornecedorDAO = new FornecedorDAO();
            FornecedorDTO objFornecedorDTO = new FornecedorDTO();
            
            ResultSet rsFornecedorDAO = objFornecedorDAO.ListaBusca(objFornecedorDTO);
            
            String[] todos = {"Id", "Razao Social", "Endereco", "Cidade", "Estado", "Email", "Telefone"};
            String[][] linhas = {};
            DefaultTableModel tableModel = new DefaultTableModel(linhas, todos){
                public boolean isCellEditable(int row, int col){
                    return false;
                }
            };
            
            Vector<Vector> dados = new Vector<>();
            while(rsFornecedorDAO.next()){
                Vector regVetor = new Vector();
                regVetor.add(rsFornecedorDAO.getInt("id_fornecedor"));
                regVetor.add(rsFornecedorDAO.getString("razaosocial_fornecedor"));
                regVetor.add(rsFornecedorDAO.getString("endereco_fornecedor"));
                regVetor.add(rsFornecedorDAO.getString("cidade_fornecedor"));
                regVetor.add(rsFornecedorDAO.getString("estado_fornecedor"));
                regVetor.add(rsFornecedorDAO.getString("email_fornecedor"));
                regVetor.add(rsFornecedorDAO.getString("telefone_fornecedor"));
                
                dados.add(regVetor);
                tableModel.addRow(regVetor);
            }
            tblFornecedor.setModel(tableModel);
        }
        catch (SQLException e){
            System.err.println(e.getMessage());
        }
    }
    
    public void setarCampos(){
        int setar = tblFornecedor.getSelectedRow();
        txtId.setText(tblFornecedor.getModel().getValueAt(setar, 0).toString());
        txtRazaoSocial.setText(tblFornecedor.getModel().getValueAt(setar, 1).toString());
        txtEndereco.setText(tblFornecedor.getModel().getValueAt(setar, 2).toString());
        txtCidade.setText(tblFornecedor.getModel().getValueAt(setar, 3).toString());
        txtEstado.setText(tblFornecedor.getModel().getValueAt(setar, 4).toString());
        txtEmail.setText(tblFornecedor.getModel().getValueAt(setar, 5).toString());
        txtTelefone.setText(tblFornecedor.getModel().getValueAt(setar, 6).toString());
    }
    
    public void AlterarCampos(){
        String razaosocial, endereco, cidade, estado, email, telefone;
        int id;
        
        razaosocial = txtRazaoSocial.getText();
        endereco = txtEndereco.getText();
        id = Integer.parseInt(txtId.getText());
        telefone=txtTelefone.getText();
        cidade=txtCidade.getText();
        estado=txtEstado.getText();
        email=txtEmail.getText();
        
        FornecedorDTO objFornecedorDTO = new FornecedorDTO();
        objFornecedorDTO.setCidade(cidade);
        objFornecedorDTO.setEndereco(endereco);
        objFornecedorDTO.setEstado(estado);
        objFornecedorDTO.setRazaosocial(razaosocial);
        objFornecedorDTO.setTelefone(telefone);
        objFornecedorDTO.setEmail(email);
        objFornecedorDTO.setId(id);
        
        FornecedorDAO objFornecedorDAO = new FornecedorDAO();
        objFornecedorDAO.AlterarFornecedor(objFornecedorDTO);
    }
    
    public void ExcluirCampos(){
        int id;
        
        id = Integer.parseInt(txtId.getText());
        
        FornecedorDTO objFornecedorDTO = new FornecedorDTO();
        objFornecedorDTO.setId(id);
        
        FornecedorDAO objFornecedorDAO = new FornecedorDAO();
        objFornecedorDAO.ExcluirFornecedor(objFornecedorDTO);
        
        preenche_busca();
    }
}
