package VIEW;


import DAO.FuncionarioDAO;
import DAO.ProdutoDAO;
import DTO.FuncionarioDTO;
import DTO.ProdutoDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class frmProdutoView extends javax.swing.JFrame {
    
    /**
     * Creates new form frmProdutoView
     */
    public frmProdutoView() {
        initComponents();
        preenche_busca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodBarras = new javax.swing.JTextField();
        btnOk2 = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btbCarregarCampos = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PRODUTO");

        jLabel5.setText("Digite o nome do Produto:");

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Valor:");

        jLabel6.setText("Codigo de Barras:");

        btnOk2.setText("Ok");
        btnOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOk2ActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Quantidade", "Valor", "Codigo de Barras"
            }
        ));
        jScrollPane1.setViewportView(tblProduto);

        jLabel7.setText("ID:");

        btbCarregarCampos.setText("CARREGAR CAMPOS");
        btbCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCarregarCamposActionPerformed(evt);
            }
        });

        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btbCarregarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(txtNomeProduto)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnOk2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLimpar))
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(txtQuantidade)
                                .addComponent(txtValor)
                                .addComponent(txtCodBarras)
                                .addComponent(jLabel7)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnExcluir))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOk2)
                            .addComponent(btnLimpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbCarregarCampos)
                            .addComponent(btnAlterar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOk2ActionPerformed
        Produto();
        preenche_busca();
    }//GEN-LAST:event_btnOk2ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
        preenche_busca();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btbCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCarregarCamposActionPerformed
        setarCampos();
        preenche_busca();
    }//GEN-LAST:event_btbCarregarCamposActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AlterarCampos();
        preenche_busca();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ExcluirCampos();
        preenche_busca();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCarregarCampos;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnOk2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void Produto(){
        String nome, quantidade, valor, codbar;
        
        nome=txtNomeProduto.getText();
        quantidade=txtQuantidade.getText();
        valor=txtValor.getText();
        codbar=txtCodBarras.getText();
        
        ProdutoDTO objProdutoDTO=new ProdutoDTO();
        objProdutoDTO.setCodbar(codbar);
        objProdutoDTO.setNome(nome);
        objProdutoDTO.setQuantidade(quantidade);
        objProdutoDTO.setValor(valor);
        
        ProdutoDAO objProdutoDAO=new ProdutoDAO();
        objProdutoDAO.cadastrarProduto(objProdutoDTO);
    }
    
    private void limparCampos(){
        txtCodBarras.setText("");
        txtNomeProduto.setText("");
        txtQuantidade.setText("");
        txtValor.setText("");
        txtId.setText("");
        
        txtNomeProduto.requestFocus();
    }
    
    public void preenche_busca(){
        try{
            ProdutoDAO objProdutoDAO = new ProdutoDAO();
            ProdutoDTO objProdutoDTO = new ProdutoDTO();
            
            ResultSet rsProdutoDAO = objProdutoDAO.ListaBusca(objProdutoDTO);
            
            String[] todos = {"Id", "Nome", "Quantidade", "Valor", "Codigo de Barras"};
            String[][] linhas = {};
            DefaultTableModel tableModel = new DefaultTableModel(linhas, todos){
                public boolean isCellEditable(int row, int col){
                    return false;
                }
            };
            
            Vector<Vector> dados = new Vector<>();
            while(rsProdutoDAO.next()){
                Vector regVetor = new Vector();
                regVetor.add(rsProdutoDAO.getInt("id_produto"));
                regVetor.add(rsProdutoDAO.getString("nome_produto"));
                regVetor.add(rsProdutoDAO.getString("quantidade_produto"));
                regVetor.add(rsProdutoDAO.getString("valor_produto"));
                regVetor.add(rsProdutoDAO.getString("codigoDeBarras_produto"));
                
                dados.add(regVetor);
                tableModel.addRow(regVetor);
            }
            tblProduto.setModel(tableModel);
        }
        catch (SQLException e){
            System.err.println(e.getMessage());
        }
    }
    
    public void setarCampos(){
        int setar = tblProduto.getSelectedRow();
        txtId.setText(tblProduto.getModel().getValueAt(setar, 0).toString());
        txtNomeProduto.setText(tblProduto.getModel().getValueAt(setar, 1).toString());
        txtQuantidade.setText(tblProduto.getModel().getValueAt(setar, 2).toString());
        txtValor.setText(tblProduto.getModel().getValueAt(setar, 3).toString());
        txtCodBarras.setText(tblProduto.getModel().getValueAt(setar, 4).toString());
    }
    
    public void AlterarCampos(){
        String nome, quantidade, valor, codbar;
        int id;
        
        nome = txtNomeProduto.getText();
        quantidade = txtQuantidade.getText();
        id = Integer.parseInt(txtId.getText());
        codbar=txtCodBarras.getText();
        valor=txtValor.getText();
        
        ProdutoDTO objProdutoDTO = new ProdutoDTO();
        objProdutoDTO.setNome(nome);
        objProdutoDTO.setQuantidade(quantidade);
        objProdutoDTO.setCodbar(codbar);
        objProdutoDTO.setValor(valor);
        objProdutoDTO.setId(id);
        
        ProdutoDAO objProdutoDAO = new ProdutoDAO();
        objProdutoDAO.AlterarProduto(objProdutoDTO);
    }
    
    public void ExcluirCampos(){
        int id;
        
        id = Integer.parseInt(txtId.getText());
        
        ProdutoDTO objProdutoDTO = new ProdutoDTO();
        objProdutoDTO.setId(id);
        
        ProdutoDAO objProdutoDAO = new ProdutoDAO();
        objProdutoDAO.ExcluirProduto(objProdutoDTO);
    }
}
